name: Entrega Continua

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: programa

      - name: Copy binary to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "main"
          target: "/home/ec2-user"

      - name: Run application on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user
      
            export DBHOST=${{ secrets.DBHOST }}
            export DBUSER=${{ secrets.DBUSER }}
            export DBPASSWORD=${{ secrets.DBPASSWORD }}
            export DBNAME=${{ secrets.DBNAME }}
            export DBPORT=${{ secrets.PORT }}
            export PORT=8000
      
            chmod +x main
            pkill -f "./main" || true
      
            nohup ./main > app.log 2>&1 < /dev/null &
            disown
      
            exit 0
